version: 2

sources:
  
  - name: ecomerce
    description: "Dados da loja de E-comerce"
    schema: dbt_dw_raw
    loader: bigquery

    tables:
      - name: avaliacoes
        description: "Tabela de avaliações dos produtos"
        columns:
          - name: cliente_id
            description: "Chave estrangeira do cliente"
            data_tests:
              - not_null
          - name: produto_id
            description: "Chave estrangeira do produto"
            data_tests:
              - not_null
          - name: nota
            description: "Nota da avaliação"
          - name: comentario
            description: "Comentário da avaliação"
          - name: data_avaliacao
            description: "Data da avaliação"

      - name: carrinho
        description: "Tabela de carrinho de compras"
        columns:
          - name: cliente_id
            description: "Chave estrangeira do cliente que fez a compra"
            data_tests:
              - not_null
          - name: produto_id
            description: "Chave estrangeira do produto comprado"
            data_tests:
              - not_null
          - name: quantidade
            description: "Quantidade do produto no carrinho"

      - name: categorias
        description: "Tabela de categorias dos produtos"
        columns:
          - name: id
            description: "Chave primária da categoria"
            data_tests:
              - not_null
              - unique
          - name: nome
            description: "Nome da categoria"

      - name: clientes
        description: "Tabela de clientes"
        columns:
          - name: id
            description: "Chave primária do cliente"
            data_tests:
              - not_null
              - unique
          - name: nome
            description: "Nome do cliente"
          - name: email
            description: "Email do cliente"
          - name: telefone
            description: "Telefone do cliente"
          - name: data_registro
            description: "Data de registro do cliente"

      - name: itens_pedidos
        description: "Tabela de itens dos pedidos"
        columns:
          - name: pedido_id
            description: "Chave estrangeira do pedido"
            data_tests:
              - not_null
          - name: produto_id
            description: "Chave estrangeira do produto"
            data_tests:
              - not_null
          - name: quantidade
            description: "Quantidade do produto no pedido"
          - name: preco_unitario
            description: "Preço unitário do produto"
          - name: subtotal
            description: "Subtotal do pedido"

      - name: pagamentos
        description: "Tabela de pagamentos"
        columns:
          - name: id
            description: "Chave primária do pagamento"
            data_tests:
              - not_null
              - unique
          - name: pedido_id
            description: "Chave estrangeira do pedido"
            data_tests:
              - not_null
          - name: valor
            description: "Valor do pagamento"
          - name: metodo
            description: "Método de pagamento"
          - name: status
            description: "Status do pagamento"
          - name: data_pagamento
            description: "Data do pagamento"

      - name: pedidos
        description: "Tabela de pedidos"
        columns:
          - name: id
            description: "Chave primária do pedido"
            data_tests:
              - not_null
              - unique
          - name: cliente_id
            description: "Chave estrangeira do cliente"
            data_tests:
              - not_null
          - name: endereco_id
            description: "Chave estrangeira do endereço"
            data_tests:
              - not_null
          - name: data_pedido
            description: "Data do pedido"
          - name: status
            description: "Status do pedido"

      - name: produtos
        description: "Tabela de produtos"
        columns:
          - name: id
            description: "Chave primária do produto"
            data_tests:
              - not_null
              - unique
          - name: nome
            description: "Nome do produto"
          - name: descricao
            description: "Descrição do produto"
          - name: categoria_id
            description: "Chave estrangeira da categoria"
            data_tests:
              - not_null
          - name: preco
            description: "Preço do produto"
          - name: marca
            description: "Marca do produto"
          - name: estoque
            description: "Quantidade em estoque"
          - name: data_cadastro
            description: "Data de cadastro do produto"
